version: 0.2

env:
  variables:
    ECR_REPOSITORY: "atslt"
    AWS_ACCOUNT_ID: "381492133980"
    AWS_REGION: "us-east-1"
    IMAGE_TAG: "latest"
    REPO_URI: "381492133980.dkr.ecr.us-east-1.amazonaws.com/atslt"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Docker..."
      - yum install -y docker
      - service docker start
      - docker --version

  pre_build:
    commands:
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPO_URI
      - echo "ECR login successful."

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t atslt .
      - echo "Tagging image..."
      - docker tag atslt:latest $REPO_URI:$IMAGE_TAG
      - echo "Pushing image to ECR..."
      - docker push $REPO_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Generating ECS task definition JSON..."
      - |
        TASK_DEFINITION_JSON=$(cat <<EOF
        {
          "family": "atslt-task-definition",
          "networkMode": "awsvpc",
          "requiresCompatibilities": ["FARGATE"],
          "cpu": "256",
          "memory": "512",
          "executionRoleArn": "arn:aws:iam::381492133980:role/ecsTaskExecutionRole",
          "containerDefinitions": [
            {
              "name": "ats-container",
              "image": "$REPO_URI:$IMAGE_TAG",
              "essential": true,
              "portMappings": [
                {
                  "containerPort": 8080,
                  "protocol": "tcp"
                }
              ]
            }
          ]
        }
        EOF
        )
      - echo "$TASK_DEFINITION_JSON" > task-definition.json
      - echo "Task definition JSON:"
      - cat task-definition.json
      - echo "Registering task definition..."
      - aws ecs register-task-definition --cli-input-json file://task-definition.json

artifacts:
  files:
    - task-definition.json

cache:
  paths:
    - "~/.m2/**/*"
