version: 0.2

env:
  variables:
    S3_BUCKET: "ats-lt-build"    # Replace with your S3 bucket name
    S3_PATH: "build"             # Folder path in the S3 bucket

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Docker..."
      - yum update -y
      - yum install -y docker  # Install Docker using yum
      - docker --version       # Verify Docker installation

  pre_build:
    commands:
      - echo "Verifying Docker installation..."
      - docker --version       # Check Docker version

  build:
    commands:
      - echo "Starting Maven build..."
      - mvn clean install  # Clean and build the Maven project
      - echo "Build completed successfully!"
      - echo "Building Docker image..."
      - docker build -t ats-lt-docker-image .  # Build Docker image from DockerFile
      - echo "Saving Docker image to a tarball..."
      - docker save ats-lt-docker-image | gzip > ats-lt-docker-image.tar.gz  # Save Docker image to tarball

  post_build:
    commands:
      - echo "Generating imagedefinitions.json for ECS deployment..."
      - IMAGE_URI="s3://$S3_BUCKET/$S3_PATH/ats-lt-docker-image.tar.gz"  # S3 path for the Docker image tarball
      - printf '[{"name":"my-container","imageUri":"%s"}]' $IMAGE_URI > imagedefinitions.json
      - echo "imagedefinitions.json generated successfully!"

      # Upload Docker image tarball and imagedefinitions.json to S3
      - aws s3 cp ats-lt-docker-image.tar.gz s3://$S3_BUCKET/$S3_PATH/ats-lt-docker-image.tar.gz
      - aws s3 cp imagedefinitions.json s3://$S3_BUCKET/$S3_PATH/imagedefinitions.json
      - echo "Docker image and imagedefinitions.json uploaded to S3 successfully!"

artifacts:
  files:
    - target/*.jar  # Include the Maven JAR file
    - ats-lt-docker-image.tar.gz  # Include the Docker image tarball
    - imagedefinitions.json        # Include the generated imagedefinitions.json
  discard-paths: yes

cache:
  paths:
    - "~/.m2/**/*"  # Cache Maven dependencies to speed up subsequent builds
