spring:
  datasource:
    url: jdbc:mysql://ats.cpoaq6w2il9y.us-east-1.rds.amazonaws.com:3306/ats-service
    username: Administrator
    password: ats-leverage2024
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: deependhar2deepu@gmail.com
    password: eriqjzbcmkplgokr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your-client-id
            client-secret: your-client-secret
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com1/oauth2/v3/userinfo
            user-name-attribute: sub




jwt:
  rsa-private-key: classpath:certs/privateKey.pem
  rsa-public-key: classpath:certs/publicKey.pem




logging:
  file:
    path: logs/
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:- %5p} %m%n"
    file: "%d %-5level [%thread] %logger :%msg%n"
  level:
    web: error
    root: info
    sql: error
    org.springframework.security: trace
    org.springframework.web: DEBUG